// bokehjs/frameworks/web-component/src/index.ts
import type {BokehMount, MountOptions} from "@bokeh/bokehjs"
import {MountController} from "@bokeh/framework"
import type {BokehModel} from "@bokeh/framework"

const HTMLElementBase = (globalThis as {HTMLElement?: typeof HTMLElement}).HTMLElement ?? class {} as typeof HTMLElement

export class BokehElement extends HTMLElementBase {
  private _model: BokehModel | null = null
  private _mount_options: MountOptions | undefined
  private _controller = new MountController()

  /** The Bokeh root, roots array, or document to render in one mount. */
  get model(): BokehModel | null {
    return this._model
  }

  set model(model: BokehModel | null) {
    if (model == this._model) {
      return
    }
    this._model = model
    if (this.isConnected) {
      this._restart()
    }
  }

  get mountOptions(): MountOptions | undefined {
    return this._mount_options
  }

  set mountOptions(options: MountOptions | undefined) {
    this._mount_options = options
    if (this.isConnected && this._model != null) {
      this._restart()
    }
  }

  connectedCallback(): void {
    this._restart()
  }

  disconnectedCallback(): void {
    this._controller.dispose()
  }

  private _restart(): void {
    this._controller.dispose()
    if (this._model == null) {
      return
    }

    this._controller = new MountController()
    void this._controller.start(this._model, this, {
      mountOptions: this._mount_options,
      onMounted: (mounted) => this.dispatchEvent(new CustomEvent<BokehMount>("bokeh-mount", {detail: mounted})),
      onDisposed: (mounted) => this.dispatchEvent(new CustomEvent<BokehMount>("bokeh-unmount", {detail: mounted})),
      onError: (error) => this.dispatchEvent(new CustomEvent("bokeh-mount-error", {detail: error})),
    })
  }
}

export function defineBokehElement(name: string = "bokeh-plot"): typeof BokehElement {
  const existing = customElements.get(name)
  if (existing != null) {
    if (existing != BokehElement && !(existing.prototype instanceof BokehElement)) {
      throw new Error(`custom element '${name}' is already defined by another constructor`)
    }
    return existing as typeof BokehElement
  }
  const DefinedBokehElement = class extends BokehElement {}
  customElements.define(name, DefinedBokehElement)
  return DefinedBokehElement
}

// bokehjs/frameworks/react/src/index.ts
import {createElement, useCallback, useEffect, useRef, useState} from "react"
import type {HTMLAttributes, ReactElement, RefCallback} from "react"

import type {BokehMount, MountOptions} from "@bokeh/bokehjs"
import {MountController} from "@bokeh/framework"
import type {BokehModel} from "@bokeh/framework"

export type UseBokehOptions = {
  mountOptions?: MountOptions
  onMounted?(mounted: BokehMount): void
  onError?(error: unknown): void
}

export type UseBokehResult = {
  ref: RefCallback<HTMLDivElement>
  mounted: BokehMount | null
  error: unknown
}

export function useBokeh(model: BokehModel | null, options: UseBokehOptions = {}): UseBokehResult {
  const [target, setTarget] = useState<HTMLDivElement | null>(null)
  const [mounted, setMounted] = useState<BokehMount | null>(null)
  const [error, setError] = useState<unknown>(null)
  const callbacks = useRef(options)
  callbacks.current = options

  const ref = useCallback<RefCallback<HTMLDivElement>>((element) => setTarget(element), [])
  const signal = options.mountOptions?.signal

  useEffect(() => {
    if (model == null || target == null) {
      return
    }

    const controller = new MountController()
    setMounted(null)
    setError(null)
    void controller.start(model, target, {
      mountOptions: callbacks.current.mountOptions,
      onMounted: (handle) => {
        setMounted(handle)
        callbacks.current.onMounted?.(handle)
      },
      onDisposed: (handle) => {
        setMounted((current) => current == handle ? null : current)
      },
      onError: (reason) => {
        setError(reason)
        callbacks.current.onError?.(reason)
      },
    })

    return () => controller.dispose()
  }, [model, target, signal])

  return {ref, mounted, error}
}

export type BokehProps = Omit<HTMLAttributes<HTMLDivElement>, "children" | "onError"> & UseBokehOptions & {
  /** The Bokeh root, roots array, or document to render in one mount. */
  model: BokehModel
}

export function Bokeh({model, mountOptions, onMounted, onError, ...attributes}: BokehProps): ReactElement {
  const {ref} = useBokeh(model, {mountOptions, onMounted, onError})
  return createElement("div", {...attributes, ref})
}
