// bokehjs/frameworks/angular/src/index.ts
import {afterNextRender, Component, EventEmitter, Input, Output, ViewChild} from "@angular/core"
import type {ElementRef, OnChanges, OnDestroy, SimpleChanges} from "@angular/core"

import {MountController} from "@bokeh/framework"
import type {BokehModel} from "@bokeh/framework"
import type {BokehMount, MountOptions} from "@bokeh/bokehjs"

@Component({
  selector: "bokeh-plot",
  standalone: true,
  template: "<div #target></div>",
  styles: ":host { display: block; }",
})
export class BokehComponent implements OnChanges, OnDestroy {
  /** The Bokeh root, roots array, or document to render in one mount. */
  @Input({required: true}) model!: BokehModel
  /** Options forwarded to Bokeh's mount() API. */
  @Input() mountOptions?: MountOptions

  @Output() readonly bokehMounted = new EventEmitter<BokehMount>()
  @Output() readonly bokehDisposed = new EventEmitter<BokehMount>()
  @Output() readonly bokehMountError = new EventEmitter<unknown>()

  @ViewChild("target", {static: true}) private _target!: ElementRef<HTMLElement>

  mounted: BokehMount | null = null

  private readonly _controller = new MountController()
  private _view_ready = false
  private _destroyed = false

  constructor() {
    afterNextRender(() => {
      if (!this._destroyed) {
        this._view_ready = true
        this._mount()
      }
    })
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (this._view_ready && (Object.hasOwn(changes, "model") || Object.hasOwn(changes, "mountOptions"))) {
      this._mount()
    }
  }

  ngOnDestroy(): void {
    this._destroyed = true
    this._controller.dispose()
    this.mounted = null
  }

  private _mount(): void {
    void this._controller.start(this.model, this._target.nativeElement, {
      mountOptions: this.mountOptions,
      onMounted: (mounted) => {
        this.mounted = mounted
        this.bokehMounted.emit(mounted)
      },
      onDisposed: (mounted) => {
        if (this.mounted == mounted) {
          this.mounted = null
        }
        this.bokehDisposed.emit(mounted)
      },
      onError: (error) => this.bokehMountError.emit(error),
    })
  }
}

// bokehjs/frameworks/web-component/src/index.ts
import type {BokehMount, MountOptions} from "@bokeh/bokehjs"
import {MountController} from "@bokeh/framework"
import type {BokehModel} from "@bokeh/framework"

const HTMLElementBase = (globalThis as {HTMLElement?: typeof HTMLElement}).HTMLElement ?? class {} as typeof HTMLElement

export class BokehElement extends HTMLElementBase {
  private _model: BokehModel | null = null
  private _mount_options: MountOptions | undefined
  private _controller = new MountController()

  /** The Bokeh root, roots array, or document to render in one mount. */
  get model(): BokehModel | null {
    return this._model
  }

  set model(model: BokehModel | null) {
    if (model == this._model) {
      return
    }
    this._model = model
    if (this.isConnected) {
      this._restart()
    }
  }

  get mountOptions(): MountOptions | undefined {
    return this._mount_options
  }

  set mountOptions(options: MountOptions | undefined) {
    this._mount_options = options
    if (this.isConnected && this._model != null) {
      this._restart()
    }
  }

  connectedCallback(): void {
    this._restart()
  }

  disconnectedCallback(): void {
    this._controller.dispose()
  }

  private _restart(): void {
    this._controller.dispose()
    if (this._model == null) {
      return
    }

    this._controller = new MountController()
    void this._controller.start(this._model, this, {
      mountOptions: this._mount_options,
      onMounted: (mounted) => this.dispatchEvent(new CustomEvent<BokehMount>("bokeh-mount", {detail: mounted})),
      onDisposed: (mounted) => this.dispatchEvent(new CustomEvent<BokehMount>("bokeh-unmount", {detail: mounted})),
      onError: (error) => this.dispatchEvent(new CustomEvent("bokeh-mount-error", {detail: error})),
    })
  }
}

export function defineBokehElement(name: string = "bokeh-plot"): typeof BokehElement {
  const existing = customElements.get(name)
  if (existing != null) {
    if (existing != BokehElement && !(existing.prototype instanceof BokehElement)) {
      throw new Error(`custom element '${name}' is already defined by another constructor`)
    }
    return existing as typeof BokehElement
  }
  const DefinedBokehElement = class extends BokehElement {}
  customElements.define(name, DefinedBokehElement)
  return DefinedBokehElement
}
